FROM python:3-alpine
MAINTAINER yumemo
WORKDIR /root
ENV HOSTNAME="flask-container" \
    PS1="[\u@\h \W]# "
ADD requirements.in /root/requirements.in
RUN apk update && \
RUN apk add --no-cache libffi-dev build-base && \
    pip install --upgrade pip && \
    pip install --upgrade setuptools && \
    pip install pip-tools && \
    pip-compile /root/requirements.in && \
    pip-sync

# pip-compile実行時にhangする
