version: '3'
services:
  db:
    image: postgres:9.6.17-alpine
    container_name: db
    tty: true
    environment:
      POSTGRES_USER: keywoo
      POSTGRES_PASSWORD: keywoo
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  keywoo:
    build: .
    image: yumemo/keywoo
    container_name: keywoo
    hostname: keywoo
    tty: true
    links:
      - db
    volumes:
      - .:/opt/keywoo
    ports:
      - "5000:5000"
    environment:
      WAIT_HOSTS: db:5432

  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - keywoo
    restart: always
    environment:
      DOMAINS: 'keywoo.tokyo -> http://keywoo:5000'
      STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'

volumes:
  database:
    driver: local