version: '3'
services:
  flask:
    build: .
    container_name: flask-container
    hostname: flask-container
    tty: true
    volumes:
      - ./app:/root/app
      - ./scripts:/root/scripts
    ports:
      - "5000:5000"
