version: '3'
services:
  db:
    image: postgres:9.6.17-alpine
    container_name: db
    environment:
      POSTGRES_USER: keywoo
      POSTGRES_PASSWORD: keywoo
    ports:
      - "5432:5432"

  keywoo:
    build: .
    image: yumemo/keywoo
    container_name: keywoo
    hostname: keywoo
    tty: true
    links:
      - db
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"

  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - keywoo
    restart: always
    environment:
      DOMAINS: 'keywoo.tokyo.local -> http://keywoo:5000'
      STAGE: 'local' # Don't use production until staging works
      # FORCE_RENEW: 'true'
