version: '3'
services:
  flask:
    restart: always
    build: .
    container_name: work-container
    hostname: work-container
    tty: true
    volumes:
      - ./app:/root/app
      - ./scripts:/root/scripts
    ports:
      - "5000:5000"
