version: '3'
services:
  python3:
    restart: always
    build: ./python3
    container_name: work-container
    hostname: work-container
    tty: true
    volumes:
      - ./scripts:/root/scripts
  web:
