name: Deploy Site
on:
  push:
    branches: [main]
jobs:
  deploy_site:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: rsync repository
      run: rsync -av --delete -o StrictHostKeyChecking=no --exclude-from=".gitignore" . keywoo@keywoo.yumenomatayume.net:~/keywoo
    - name: restart compose
      run: |
        ssh -o StrictHostKeyChecking=no keywoo@keywoo.yumenomatayume.net "cd keywoo && sudo docker-compose restart"
