name: SSH deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ssh_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: rsync repository
      run: rsync -acvz --delete . keywoo@keywoo.tokyo:/opt/keywoo